version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    env_file:
      - ./.env
    ports:
      - "${HOST_PORT}:${PORT}"
    depends_on:
      - "mongo"
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
  