#Primeira camada: build do diretório /app/dist
FROM node:14-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

RUN npm run build

#Segunda camada: instalação apenas dos pacotes usados produção e remoção do cache
FROM node:14-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --only-production && npm cache clean --force

COPY . ./ 

COPY --from=builder /app/dist/ ./dist/

CMD node dist/server.js
