version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: ./Dockerfile.prod
    env_file:
      - ./.env
    ports:
      - "${HOST_PORT}:${PORT}"
    depends_on:
      - "mongo"
  mongo:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
  